services:
  - type: web
    name: alex-pikuV2
    env: node
    branch: main
    repo: https://github.com/ricky806/alex-pikuV2.git
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: false
    envVars:
      - key: SESSION_ID
        sync: false
      - key: BOT_INFO
        value:Ã€ğ–‘Ã¨ğ– ğ•»Ã¬ğ–Ã¹ ËÍ¢Â»;Ã€ğ–‘Ã¨ğ– ğ•»Ã¬ğ–Ã¹ ËÍ¢Â»;https://i.imgur.com/LOA5drs.mp4
      - key: ALWAYS_ONLINE
        value: true
      - key: AUTO_STATUS_VIEWS
        value: true
      - key: AUDIO_DATA
        value: Ã€ğ–‘Ã¨ğ– ğ•»Ã¬ğ–Ã¹ËÍ¢Â»;Ã€ğ–‘Ã¨ğ– ğ•»Ã¬ğ–Ã¹ËÍ¢Â»;https://i.imgur.com/LOA5drs.mp4
      - key: HANDLER
        value: /
      - key: WORK_TYPE
        value: private
      - key: SERVER
        value: render
      - key: CAPTION
        value: Ã€ğ–‘Ã¨ğ– ğ•»Ã¬ğ–Ã¹ËÍ¢Â»
      - key: STICKER_DATA
        value: Ã€ğ–‘Ã¨ğ– ğ•»Ã¬ğ–Ã¹ËÍ¢Â»;Ã€ğ–‘Ã¨ğ– ğ•»Ã¬ğ–Ã¹ËÍ¢Â»
      - key: SUDO
        value: 918536881026
      - key: SERVERURL
        value:
      - key: DATABASE_URL
        sync: false
      - key: LOGS
        value: true 
